INSERT INTO T_NOTIFICATION_TOKEN(token, user_id) VALUES ('token_1', 1);
INSERT INTO T_NOTIFICATION_TOKEN(token, user_id) VALUES ('token_1', 2);
INSERT INTO T_NOTIFICATION_TOKEN(token, user_id) VALUES ('token_2', 2);
INSERT INTO T_NOTIFICATION_TOKEN(token, user_id) VALUES ('token_3', 3);
INSERT INTO T_NOTIFICATION_TOKEN(token, user_id) VALUES ('token_4', 4);
INSERT INTO T_NOTIFICATION_TOKEN(token, user_id) VALUES ('token_5', 5);

INSERT INTO T_NOTIFICATION(id, content, date, title, user_id) VALUES(1, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 1);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(2, 'Esto es una prueba.', '2024-08-23', 'Test notificación', 1);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(3, 'Esto es una prueba.', '2024-08-22', 'Test notificación', 1);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(4, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 2);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(5, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 3);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(6, 'Esto es una prueba.', '2024-08-22', 'Test notificación', 3);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(7, 'Esto es una prueba.', '2024-08-20', 'Test notificación', 3);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(8, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 8);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(9, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 9);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(10, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 13);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(11, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 23);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(12, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 33);
INSERT INTO T_NOTIFICATION(id, content, date, title, user_id)  VALUES(13, 'Esto es una prueba.', '2024-08-25', 'Test notificación', 12);