name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: prueba
          POSTGRES_USER: prueba
          POSTGRES_PASSWORD: prueba
        options: >-
          --health-cmd "pg_isready -U prueba" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Wait for PostgreSQL to be ready
      run: until pg_isready -h localhost -p 5432 -U prueba; do sleep 1; done

    - name: Run tests
      run: ./mvnw clean dependency:resolve test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/prueba
        SPRING_DATASOURCE_USERNAME: prueba
        SPRING_DATASOURCE_PASSWORD: prueba
